gauge <- read.csv("~/Documents/gauge.txt", sep="")
View(gauge)
plot(gauge)
fit <- lm(formula=gain~density, data=gauge) 
fit 
abline(fit, col="red") 
plot(fit$residuals) 
abline(0, 0, col="red") 
hist(fit$residuals) 
qqnorm(fit$residuals) 
qqline(fit$residuals, col="red") 
plot(fit$residuals) 
abline(0, 0, col="red") 
R.square <- sum((fit$fitted.values-mean(gauge$gain))^2) / (sum((gauge$gain - mean(gauge$gain))^2)) 
summary(fit)

attach(gauge) 
plot(density,log(gain))
fit <- lm(formula=log(gain)~density, data=gauge) 
fit 
abline(fit, col="red") 
plot(fit$residuals) 
abline(0, 0, col="red") 
hist(fit$residuals) 
qqnorm(fit$residuals) 
qqline(fit$residuals, col="red") 
plot(fit$residuals) 
abline(0, 0, col="red") 
R.square <- sum(fit$fitted.values-mean(gauge$gain)^2 / (sum(gauge$gain) - mean(gauge$gain)^2)) 
summary(fit)

density.lm = lm(density ~ log(gain)) 
newdata = data.frame(gain=38.6) 
predict(density.lm, newdata, interval="confidence", level=.95) 
newdata2 = data.frame(gain=426.7) 
predict(density.lm, newdata2, interval="confidence")


predict(density.lm, newdata, interval="prediction")

predict(density.lm, newdata2, interval="prediction")
plot(gauge) 
attach(gauge) 
plot (density, log(gain)) 
fit.log = lm(formula = log(gain)~density, data = gauge)  
abline(fit.log, col = "red")  
install.packages("quantreg") 
library(quantreg) 
fit2 <- rq(formula = log(gain)~density, tau=.025, data=gauge) 
abline(fit2, col="blue") 
fit3 <- rq(formula = log(gain)~density, tau=.975, data=gauge) 
abline(fit3, col="green")
gauge.valid1 = gauge[-c(21:30),] 
gauge.valid2 = gauge[-c(81:90),] 

plot(gauge.valid1$density, log(gauge.valid1$gain)) 
fit.log = lm(formula = log(gauge.valid1$gain)~gauge.valid1$density, data = gauge.valid1) 
abline(fit.log, col = "red") 
fit.lower = rq(formula = log(gauge.valid1$gain)~gauge.valid1$density, tau = .025, data = gauge.valid1) 
abline(fit.lower, col = "blue") 
fit.upper = rq(formula = log(gauge.valid1$gain)~gauge.valid1$density, tau = .975, data = gauge.valid1) 
abline(fit.upper, col = "blue") 

plot(gauge.valid2$density, log(gauge.valid2$gain), xlim = c(0,0.7), ylim = c(3.0,6.0)) 
fit.log = lm(formula = log(gauge.valid2$gain)~gauge.valid2$density, data = gauge.valid2) 
abline(fit.log, col = "red") 
fit.lower = rq(formula = log(gauge.valid2$gain)~gauge.valid2$density, tau = .025, data = gauge.valid2) 
abline(fit.lower, col = "blue") 
fit.upper = rq(formula = log(gauge.valid2$gain)~gauge.valid2$density, tau = .975, data = gauge.valid2) 
abline(fit.upper, col = "blue")
attach(gauge.valid1) 
densityvalid1.lm = lm(density ~ log(gain)) 
newdatavalid1 = data.frame(gain=38.6) 
predict(densityvalid1.lm, newdatavalid1, interval="confidence")
predict(densityvalid1.lm, newdatavalid1, interval="prediction")
densityvalid1.lm = lm(density ~ log(gain)) 
newdatavalid2 = data.frame(gain=426.7) 
predict(densityvalid1.lm, newdatavalid2, interval="confidence")
predict(densityvalid1.lm, newdatavalid2, interval="prediction")

attach(gauge.valid2) 
densityvalid2.lm = lm(density ~ log(gain)) 
newdatavalid1 = data.frame(gain=38.6) 
predict(densityvalid2.lm, newdatavalid1, interval="confidence")
predict(densityvalid2.lm, newdatavalid1, interval="prediction")
newdatavalid2 = data.frame(gain=426.7) 
predict(densityvalid2.lm, newdatavalid2, interval="confidence")
predict(densityvalid2.lm, newdatavalid2, interval="prediction")
